### ISSUE TITLE
Limit and Skip?

### ISSUE THREAD

**Issue by manuel-rubio** [mkrogemann/couchdb_connector#47]
Hi, I'm trying to use the query parameters `skip` and `limit` to paginate an output, did you implement them in any way?

Example:

```
http://localhost:5984/db/_design/d/_view/random?skip=i&limit=1
```

**Comment by mkrogemann** [comment]
Hi and thank you for your contribution. Sorry for taking so long to reply, I will have to update my github settings to make sure to receive more E-Mails.

I have not considered skip and limit so far. 

I saw that your PR build failed but I think there was no problem with the code you contributed and I was just now able to successfully re-run the tests.

I will have a closer look at your PR next.
